<?php $this->headTitle(sprintf('Add new %s', $this->translate('service'))) ?>

<div class="page-header">
    <h1 id="services">
        <span class="glyphicon glyphicon-cutlery"></span> <?= $this->escapeHtml($this->translate('Services')) ?>
    </h1>
</div>

<div class="well">
    <?= $this->form()->openTag($form) ?>
    <fieldset>
        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('summary')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('summary')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate(sprintf('Original "%s" summary.', $fallbackLocaleName))) ?>
                </div>
            </div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('summary'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('price')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('price')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('price'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('currency')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('currency')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('currency'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('description')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('description')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate(sprintf('Original "%s" description.', $fallbackLocaleName))) ?>
                </div>
            </div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('description'), ['class' => 'help-block']) ?>
            </div>
        </div>
    </fieldset>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <button class="btn btn-primary" type="submit" name="add">
                <span class="glyphicon glyphicon-edit"></span> <?= $this->escapeHtml($this->translate(sprintf('Add new %s', $this->translate('service')))) ?>
            </button>
        </div>
    </div>
    <?= $this->form()->closeTag() ?>
</div>
