<?php $this->headTitle(sprintf('Edit %s', $this->translate('service'))) ?>

<div class="page-header">
    <h1 id="services">
        <span class="glyphicon glyphicon-cutlery"></span> <?= $this->escapeHtml($this->translate('Services')) ?>
    </h1>
</div>

<div class="well">
    <?= $this->form()->openTag($form) ?>
    <fieldset>
        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('summary')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('summary')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate(sprintf('Original "%s" summary.', $fallbackLocaleName))) ?>
                </div>
            </div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('summary'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('price')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('price')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('price'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('currency')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('currency')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('currency'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('description')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('description')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate(sprintf('Original "%s" description.', $fallbackLocaleName))) ?>
                </div>
            </div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('description'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <?php
        $url = $this->url('administrationService', ['action' => 'edit', 'id' => $id, 'translationLocale' => 'none']);
        $form->get('translationLocale')->setAttributes([
            'value' => $translationLocale,
            'onchange' => 'document.location.href=("' . $url . '").replace("none", this.value)'
        ]);
        ?>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('translationLocale')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('translationLocale')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate('Supported languages.')) ?>
                </div>
            </div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('translationLocale'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <?php if ($translationLocale != 'none') { ?>
            <div class="form-group right required">
                <div class="col-sm-3"><?= $this->formLabel($form->get('translationSummary')) ?></div>
                <div class="col-sm-9"><?= $this->formElement($form->get('translationSummary')) ?></div>
                <div class="col-sm-offset-3 col-sm-9">
                    <div class="help-block nobottom">
                        <?= $this->escapeHtml($this->translate(sprintf('Translated "%s" summary.', $translationName))) ?>
                    </div>
                </div>
                <div class="col-sm-offset-3 col-sm-9">
                    <?= $this->formElementErrors($form->get('translationSummary'), ['class' => 'help-block']) ?>
                </div>
            </div>

            <div class="form-group right">
                <div class="col-sm-3"><?= $this->formLabel($form->get('translationDescription')) ?></div>
                <div class="col-sm-9"><?= $this->formElement($form->get('translationDescription')) ?></div>
                <div class="col-sm-offset-3 col-sm-9">
                    <div class="help-block nobottom">
                        <?= $this->escapeHtml($this->translate(sprintf('Translated "%s" description.', $translationName))) ?>
                    </div>
                </div>
                <div class="col-sm-offset-3 col-sm-9">
                    <?= $this->formElementErrors($form->get('translationDescription'), ['class' => 'help-block']) ?>
                </div>
            </div>
        <?php } ?>
    </fieldset>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <button class="btn btn-primary" type="submit" name="edit">
                <span class="glyphicon glyphicon-edit"></span> <?= $this->escapeHtml($this->translate(sprintf('Edit %s', $this->translate('service')))) ?>
            </button>
        </div>
    </div>
    <?= $this->form()->closeTag() ?>
</div>
