<?php
$this->headTitle($this->escapeHtml($this->translate('Home')));
?>

<div class="well nobottom">
    <ul style="list-style-type: none;padding: 0">
        <?php if ($company['fullName']) { ?>
            <li style="padding-bottom: 5px">
                <strong><?= $this->escapeHtml($company['fullName']) ?></strong>
            </li>
        <?php } ?>
        <?php if ($company['address']) { ?>
            <li>
                <span class="glyphicon glyphicon-home"></span> <?= $this->escapeHtml($company['address']) ?>
            </li>
        <?php } ?>
        <?php if ($company['email']) { ?>
            <li>
                <span class="glyphicon glyphicon-envelope"></span> <?= $this->escapeHtml($company['email']) ?>
            </li>
        <?php } ?>
        <?php if ($company['phone']) { ?>
            <li>
                <span class="glyphicon glyphicon-phone-alt"></span> <?= $this->escapeHtml($company['phone']) ?>
            </li>
        <?php } ?>
    </ul>
    <?php if ($google['enable']) { ?>
        <div id="map" class="google-map"></div>
    <?php } ?>
</div>
<?php if ($google['enable']) { ?>
    <script>
        function initMap() {
            var uluru = {lat: <?= $this->escapeHtml($google['latitude']) ?>, lng: <?= $this->escapeHtml($google['longitude']) ?>};
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: <?= $this->escapeHtml($google['zoom']) ?>,
                center: uluru
            });
            var marker = new google.maps.Marker({
                position: uluru,
                map: map
            });
        }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?callback=initMap">
    </script>
<?php } ?>
