<?php $this->headTitle($this->escapeHtml($this->translate('Look & feel'))) ?>

<div class="card shadow rounded mb-2 bg-default">
    <div class="card-body">

        <?= $this->form()->openTag($form) ?>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb border border-secondary shadow-sm mb-2 p-2">
                <li class="mr-2"><span class="if if-look bg-default border border-secondary rounded-circle p-2 m-n1"></span></li>
                <li class="breadcrumb-item active" aria-current="page"><?= $this->escapeHtml($this->translate('Look & feel')) ?></li>
            </ol>
        </nav>

        <div class="card mb-2 bg-default">
            <div class="card-body" style="overflow: auto; height: calc(100vh - 13rem)">

                <div class="border-bottom pb-1 mb-3">
                    <?= $this->escapeHtml($this->translate('Theme & look')) ?>
                </div>

                <div class="form-row px-3">
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('theme')) ?>
                        <?= $this->formElement($form->get('theme')) ?>
                        <?= $this->formElementErrors($form->get('theme'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('barStyle')) ?>
                        <?= $this->formElement($form->get('barStyle')) ?>
                        <?= $this->formElementErrors($form->get('barStyle'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                </div>

                <div class="border-bottom pb-1 mb-3">
                    <?= $this->escapeHtml($this->translate('OpenStreetMap')) ?>
                </div>

                <div class="form-row px-3">
                    <div class="form-group col-md-6">
                        <div class="custom-control custom-checkbox">
                            <?= $this->formElement($form->get('enableMap')) ?>
                            <?= $this->formLabel($form->get('enableMap')) ?>
                            <?= $this->formElementErrors($form->get('enableMap'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('mapZoom')) ?>
                        <?= $this->formElement($form->get('mapZoom')) ?>
                        <?= $this->formElementErrors($form->get('mapZoom'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                        <div class="text-muted">
                            <?= $this->escapeHtml($this->translate('15 is generally good zoom value.')) ?>
                        </div>
                    </div>
                </div>

                <div class="border-bottom pt-2 pb-1 mb-3">
                    <?= $this->escapeHtml($this->translate('View settings')) ?>
                </div>

                <div class="form-row px-3">
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('rowsPerPage')) ?>
                        <?= $this->formElement($form->get('rowsPerPage')) ?>
                        <?= $this->formElementErrors($form->get('rowsPerPage'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('photosPerPage')) ?>
                        <?= $this->formElement($form->get('photosPerPage')) ?>
                        <?= $this->formElementErrors($form->get('photosPerPage'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                </div>

                <div class="form-row px-3">
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('roomsPerPage')) ?>
                        <?= $this->formElement($form->get('roomsPerPage')) ?>
                        <?= $this->formElementErrors($form->get('roomsPerPage'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('photoThumbnailWidth')) ?>
                        <?= $this->formElement($form->get('photoThumbnailWidth')) ?>
                        <?= $this->formElementErrors($form->get('photoThumbnailWidth'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                </div>

            </div>
        </div>

        <button type="submit" id="update" name="update" class="btn btn-primary">
            <span class="if if-update"></span><?= $this->escapeHtml($this->translate('Update look & feel')) ?>
        </button>

        <?= $this->form()->closeTag() ?>

    </div>
</div>
