<?php $this->headTitle($this->escapeHtml($this->translate('General settings'))) ?>

<div class="card shadow rounded mb-2 bg-default">
    <div class="card-body">

        <?= $this->form()->openTag($form) ?>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb border border-secondary shadow-sm mb-2 p-2">
                <li class="mr-2"><span class="if if-settings bg-white border border-secondary rounded-circle p-2 m-n1"></span></li>
                <li class="breadcrumb-item active" aria-current="page"><?= $this->escapeHtml($this->translate('General settings')) ?></li>
            </ol>
        </nav>

        <div class="card mb-2 bg-default">
            <div class="card-body" style="overflow: auto; height: calc(100vh - 13rem)">

                <div class="border-bottom pb-1 mb-3">
                    <?= $this->escapeHtml($this->translate('Company information')) ?>
                </div>

                <div class="form-row px-3">
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('companyName')) ?>
                        <?= $this->formElement($form->get('companyName')) ?>
                        <?= $this->formElementErrors($form->get('companyName'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('companyFullName')) ?>
                        <?= $this->formElement($form->get('companyFullName')) ?>
                        <?= $this->formElementErrors($form->get('companyFullName'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                </div>

                <div class="form-row px-3">
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('companyAddress')) ?>
                        <?= $this->formElement($form->get('companyAddress')) ?>
                        <?= $this->formElementErrors($form->get('companyAddress'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('companyEmail')) ?>
                        <?= $this->formElement($form->get('companyEmail')) ?>
                        <?= $this->formElementErrors($form->get('companyEmail'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                </div>

                <div class="form-row px-3">
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('companyPhone')) ?>
                        <?= $this->formElement($form->get('companyPhone')) ?>
                        <?= $this->formElementErrors($form->get('companyPhone'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('currency')) ?>
                        <?= $this->formElement($form->get('currency')) ?>
                        <?= $this->formElementErrors($form->get('currency'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                </div>

                <div class="border-bottom pt-2 pb-1 mb-3">
                    <?= $this->escapeHtml($this->translate('Upload settings')) ?>
                </div>

                <div class="form-row px-3">
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('jpegQuality')) ?>
                        <?= $this->formElement($form->get('jpegQuality')) ?>
                        <?= $this->formElementErrors($form->get('jpegQuality'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                        <div class="text-muted">
                            <?= $this->escapeHtml($this->translate('Quality of the images. 1 is the lowest, 100 is the highest.')) ?>
                        </div>
                    </div>
                </div>

                <div class="form-row px-3">
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('photoMinSize')) ?>
                        <?= $this->formElement($form->get('photoMinSize')) ?>
                        <?= $this->formElementErrors($form->get('photoMinSize'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                        <div class="text-muted">
                            <?= $this->escapeHtml($this->translate('Minimum width or height of the uploadable photo.')) ?>
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('photoMinSize')) ?>
                        <?= $this->formElement($form->get('photoMinSize')) ?>
                        <?= $this->formElementErrors($form->get('photoMinSize'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                        <div class="text-muted">
                            <?= $this->escapeHtml($this->translate('Maximum width or height of the uploadable photo.')) ?>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <button type="submit" id="update" name="update" class="btn btn-primary">
            <span class="if if-update"></span><?= $this->escapeHtml($this->translate('Update settings')) ?>
        </button>

        <?= $this->form()->closeTag() ?>

    </div>
</div>
