<?php $this->headTitle($this->escapeHtml($this->translate('Add new room'))) ?>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <strong><span class="glyphicon glyphicon-bed"></span> <?= $this->escapeHtml($this->translate('Rooms')) ?>:</strong>
        <li class="breadcrumb-item"><a href="<?= $this->url('administrationRoom') ?>"><?= $this->escapeHtml($this->translate('List of rooms')) ?></a></li>
        <li class="breadcrumb-item active" aria-current="page"><?= $this->escapeHtml($this->translate('Add new room')) ?></li>
    </ol>
</nav>

<div class="well">
    <?= $this->form()->openTag($form) ?>

    <fieldset>
        <legend><?= $this->escapeHtml($this->translate('Add new room')) ?></legend>

        <div class="form-group right required">
            <div class="col-sm-3"><?= sprintf($this->formLabel($form->get('price')), $currency) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('price')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('price'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-offset-3 col-sm-9">
                <div class="btn-group">
                    <button type="button" class="btn btn-default btn-sm dropdown-toggle disabled" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-globe"></span> <?= $defaultLocaleDisplayName ?> <span class="caret"></span>
                    </button>
                </div>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('summary')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('summary')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('summary'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('description')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('description')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('description'), ['class' => 'help-block']) ?>
            </div>
        </div>
    </fieldset>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?= $this->formButton()->openTag($form->get('add')) ?>
            <span class="glyphicon glyphicon-edit"></span> <?= $this->escapeHtml($this->translate('Add new room')) ?>
            <?= $this->formButton()->closeTag() ?>
        </div>
    </div>

    <?= $this->form()->closeTag() ?>
</div>
