<?php $this->headTitle(sprintf('Edit %s', $this->translate('room'))) ?>

<div class="row" style="padding-top: 15px;">
    <div class="col-md-8 center-block" style="float:none">
        <div class="well">
            <?= $this->form()->openTag($form) ?>
            <fieldset>
                <legend><?= $this->escapeHtml($this->translate(sprintf('Edit %s', $this->translate('room')))) ?></legend>

                <div class="form-group right required">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('summary')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('summary')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <div class="help-block nobottom">
                            <?= $this->escapeHtml($this->translate(sprintf('Original "%s" summary.', $fallbackLocaleName))) ?>
                        </div>
                    </div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('summary'), ['class' => 'help-block']) ?>
                    </div>
                </div>

                <div class="form-group right required">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('price')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('price')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('price'), ['class' => 'help-block']) ?>
                    </div>
                </div>

                <div class="form-group right required">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('currency')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('currency')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('currency'), ['class' => 'help-block']) ?>
                    </div>
                </div>

                <div class="form-group right">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('description')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('description')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <div class="help-block nobottom">
                            <?= $this->escapeHtml($this->translate(sprintf('Original "%s" description.', $fallbackLocaleName))) ?>
                        </div>
                    </div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('description'), ['class' => 'help-block']) ?>
                    </div>
                </div>

                <?php
                $url = $this->url('admin-rooms', ['action' => 'edit', 'id' => $id, 'translation' => 'none']);
                $form->get('translationLocale')->setAttributes([
                    'value' => $translation,
                    'onchange' => 'document.location.href=("' . $url . '").replace("none", this.value)'
                ]);
                ?>

                <div class="form-group right">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('translationLocale')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('translationLocale')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <div class="help-block nobottom">
                            <?= $this->escapeHtml($this->translate('Supported languages.')) ?>
                        </div>
                    </div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('translationLocale'), ['class' => 'help-block']) ?>
                    </div>
                </div>

                <?php if ($translation != 'none') { ?>
                    <div class="form-group right required">
                        <div class="col-sm-3"><?= $this->formLabel($form->get('translationSummary')) ?></div>
                        <div class="col-sm-9"><?= $this->formElement($form->get('translationSummary')) ?></div>
                        <div class="col-sm-offset-3 col-sm-9">
                            <div class="help-block nobottom">
                                <?= $this->escapeHtml($this->translate(sprintf('Translated "%s" summary.', $translationName))) ?>
                            </div>
                        </div>
                        <div class="col-sm-offset-3 col-sm-9">
                            <?= $this->formElementErrors($form->get('translationSummary'), ['class' => 'help-block']) ?>
                        </div>
                    </div>

                    <div class="form-group right">
                        <div class="col-sm-3"><?= $this->formLabel($form->get('translationDescription')) ?></div>
                        <div class="col-sm-9"><?= $this->formElement($form->get('translationDescription')) ?></div>
                        <div class="col-sm-offset-3 col-sm-9">
                            <div class="help-block nobottom">
                                <?= $this->escapeHtml($this->translate(sprintf('Translated "%s" description.', $translationName))) ?>
                            </div>
                        </div>
                        <div class="col-sm-offset-3 col-sm-9">
                            <?= $this->formElementErrors($form->get('translationDescription'), ['class' => 'help-block']) ?>
                        </div>
                    </div>
                <?php } ?>

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <button class="btn btn-primary" type="submit" name="edit">
                            <span class="glyphicon glyphicon-edit"></span> <?= $this->escapeHtml($this->translate(sprintf('Edit %s', $this->translate('room')))) ?>
                        </button>
                    </div>
                </div>
            </fieldset>
            <?= $this->form()->closeTag() ?>
        </div>
    </div>
</div>
