<?php

use Application\Service\Room\RoomQueryManager;

$this->headTitle($this->escapeHtml($this->translate('Rooms')));

$form->setAttributes([
    'onsubmit' => 'return confirm(' . $this->escapeHtml($this->translate('Do you really want to delete room(s)?')) . ')'
]);
?>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <strong><span class="glyphicon glyphicon-bed"></span> <?= $this->escapeHtml($this->translate('Rooms')) ?>:</strong>
        <li class="breadcrumb-item active" aria-current="page"><?= $this->escapeHtml($this->translate('List of rooms')) ?></li>
    </ol>
</nav>

<div class="well nobottom">
    <?= $this->form()->openTag($form) ?>

    <fieldset>
        <legend><?= $this->escapeHtml($this->translate('List of rooms')) ?></legend>

        <div style="overflow: auto visible">
            <div class="btn-group">
                <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-globe"></span> <?= $locales[$this->roomQueryManager->getLocaleId()] ?> <span class="caret"></span>
                </button>

                <ul class="dropdown-menu" style="max-height: 10em; overflow: auto">
                    <?php
                    foreach ($locales as $id => $name) {
                        if ($id != $this->roomQueryManager->getLocaleId()) {
                            $queryParams = $this->roomQueryManager->getParams();
                            $queryParams['localeId'] = $id;
                            ?><li><a href="<?= $this->url(NULL, [], ['query' => $queryParams]) ?>"><?= $name ?></a></li><?php
                        }
                    }
                    ?>
                </ul>
            </div>
            <a class="btn btn-default btn-sm" href="<?= $this->url(NULL, ['action' => 'add']) ?>" style="white-space: nowrap">
                <span class="glyphicon glyphicon-plus"></span> <?= $this->escapeHtml($this->translate('Add new room')) ?>
            </a>
            <span class="btn btn-default btn-sm" onclick="(function () {
                        $('input[name=\'rooms&#x5B;&#x5D;\']').click();
                    })()">
                <span class="glyphicon glyphicon-random"></span> <?= $this->escapeHtml($this->translate('Inverse select')) ?>
            </span>
            <?= $this->formButton()->openTag($form->get('remove')) ?>
            <span class="glyphicon glyphicon-trash"></span> <?= $this->escapeHtml($this->translate('Remove selected')) ?>
            <?= $this->formButton()->closeTag() ?>

            <table id="room-table" class="table table-hover button-th nobottom">
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th>
                            <?php
                            $icon = '';
                            $queryParams = $this->roomQueryManager->getParams();
                            if ($queryParams['orderBy'] == RoomQueryManager::ORDER_BY_ID) {
                                $icon = $queryParams['order'] == RoomQueryManager::ORDER_ASC ? '-by-attributes' : '-by-attributes-alt';
                                $queryParams['order'] = $queryParams['order'] == RoomQueryManager::ORDER_ASC ? RoomQueryManager::ORDER_DESC : RoomQueryManager::ORDER_ASC;
                            } else {
                                $queryParams['orderBy'] = RoomQueryManager::ORDER_BY_ID;
                                $queryParams['order'] = RoomQueryManager::ORDER_ASC;
                            }
                            ?>
                            <a class="btn btn-default btn-sm btn-block" href="<?= $this->url(NULL, [], ['query' => $queryParams]) ?>">
                                <span class="glyphicon glyphicon-sort<?= $icon ?>"></span>
                            </a>
                        </th>
                        <th>
                            <?php
                            $icon = '';
                            $queryParams = $this->roomQueryManager->getParams();
                            if ($queryParams['orderBy'] == RoomQueryManager::ORDER_BY_SUMMARY) {
                                $icon = $queryParams['order'] == RoomQueryManager::ORDER_ASC ? '-by-attributes' : '-by-attributes-alt';
                                $queryParams['order'] = $queryParams['order'] == RoomQueryManager::ORDER_ASC ? RoomQueryManager::ORDER_DESC : RoomQueryManager::ORDER_ASC;
                            } else {
                                $queryParams['orderBy'] = RoomQueryManager::ORDER_BY_SUMMARY;
                                $queryParams['order'] = RoomQueryManager::ORDER_ASC;
                            }
                            ?>
                            <a class="btn btn-default btn-sm btn-block" href="<?= $this->url(NULL, [], ['query' => $queryParams]) ?>">
                                <?= $this->escapeHtml($this->translate('Summary')) ?> <span class="glyphicon glyphicon-sort<?= $icon ?>"></span>
                            </a>
                        </th>
                        <th>
                            <?php
                            $icon = '';
                            $queryParams = $this->roomQueryManager->getParams();
                            if ($queryParams['orderBy'] == RoomQueryManager::ORDER_BY_PRICE) {
                                $icon = $queryParams['order'] == RoomQueryManager::ORDER_ASC ? '-by-attributes' : '-by-attributes-alt';
                                $queryParams['order'] = $queryParams['order'] == RoomQueryManager::ORDER_ASC ? RoomQueryManager::ORDER_DESC : RoomQueryManager::ORDER_ASC;
                            } else {
                                $queryParams['orderBy'] = RoomQueryManager::ORDER_BY_PRICE;
                                $queryParams['order'] = RoomQueryManager::ORDER_ASC;
                            }
                            ?>
                            <a class="btn btn-default btn-sm btn-block" href="<?= $this->url(NULL, [], ['query' => $queryParams]) ?>">
                                <?= $this->escapeHtml($this->translate('Price')) ?> <span class="glyphicon glyphicon-sort<?= $icon ?>"></span>
                            </a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $decimalFormatter = new \NumberFormatter(NULL, \NumberFormatter::CURRENCY);
                    $decimalFormatter->setAttribute(\NumberFormatter::FRACTION_DIGITS, 2);
                    foreach ($rooms as $room) {
                        ?>
                        <tr class="active" data-lnk="<?= $this->url(NULL, ['action' => 'edit', 'id' => $room->getId()], $this->roomQueryManager->getLocaleId() == 1 ? [] : ['query' => ['localeId' => $this->roomQueryManager->getLocaleId()]]) ?>" style="cursor:pointer">
                            <td class="td-checkbox" data-select="true" data-button="#remove">
                                <label>
                                    <input class="icon-checkbox" type="checkbox" name="rooms&#x5B;&#x5D;" value="<?= $room->getId() ?>">
                                </label>
                            </td>
                            <td><?= $this->escapeHtml($room->getId()) ?></td>
                            <td>
                                <?php
                                $localeId = $this->roomQueryManager->getLocaleId();
                                $summary = $room->getTranslations()->containsKey($localeId) ? $room->getTranslations()->get($localeId)->getSummary() : $this->translate('*** undefined ***');
                                echo $this->escapeHtml($summary);
                                ?>
                            </td>
                            <td><?= $this->escapeHtml($decimalFormatter->formatCurrency($room->getPrice(), $currency)) ?></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </fieldset>

    <?= $this->form()->closeTag() ?>
</div>

<?= $this->paginationControl($rooms, 'Sliding', 'paginator/paginator', ['route' => NULL, 'queryParams' => $this->roomQueryManager->getParams()]) ?>
