<?php
$this->headTitle($this->escapeHtml($this->translate('Selected pictures')));
$this->breadcrumbs()->setItems([
    ['label' => 'Rooms', 'icon' => 'bed'],
    ['label' => 'List of rooms', 'url' => ['administrationRoom', []]],
    ['label' => 'Edit room', 'url' => ['administrationRoom', ['action' => 'edit', 'id' => $id]]],
    ['label' => 'List of selected pictures', 'active' => TRUE],
]);
?>

<?= $this->breadcrumbs()->render() ?>

<div class="well nobottom">
    <?= $this->form()->openTag($form) ?>

    <fieldset>
        <legend><?= $this->escapeHtml($this->translate('List of selected pictures')) ?></legend>

        <div style="overflow: auto visible">
            <a class="btn btn-default btn-sm" href="<?= $this->url(NULL, ['action' => 'availablePictures', 'id' => $id]) ?>" style="white-space: nowrap">
                <span class="glyphicon glyphicon-filter"></span> <?= $this->escapeHtml($this->translate('Show available pictures')) ?>
            </a>
            <span class="btn btn-default btn-sm" onclick="(function () {
                        $('input[name=\'pictures&#x5B;&#x5D;\']').click();
                    })()">
                <span class="glyphicon glyphicon-random"></span> <?= $this->escapeHtml($this->translate('Inverse select')) ?>
            </span>
            <?= $this->formButton()->openTag($form->get('remove')) ?>
            <span class="glyphicon glyphicon-minus"></span> <?= $this->escapeHtml($this->translate('Remove selected from room')) ?>
            <?= $this->formButton()->closeTag() ?>

            <p>
                <?php foreach ($pictures as $picture) { ?>
                <div class="img-thumbnail">
                    <img src="<?= $this->url('administrationPicture', ['action' => 'thumbnail', 'id' => $picture->getId()]) ?>" width="<?= $this->thumbnailWidth ?>">
                    <div class="caption caption-checkbox" data-button="#remove">
                        <label>
                            <input class="icon-checkbox" type="checkbox" name="pictures&#x5B;&#x5D;" value="<?= $picture->getId() ?>"><?= $picture->getId() ?>
                        </label>
                    </div>
                </div>
            <?php } ?>
            </p>
        </div>
    </fieldset>

    <?= $this->form()->closeTag() ?>
</div>

<?= $this->paginationControl($pictures, 'Sliding', 'paginator/paginator', ['route' => NULL, 'params' => ['action' => 'selectedPictures'], 'queryParams' => $this->pictureQueryManager->getParams()]) ?>
