<?php
$this->headTitle($this->escapeHtml($this->translate('Rooms')));
$this->breadcrumbs()->setItems([
    ['label' => 'Rooms', 'icon' => 'bed'],
    ['label' => 'List of rooms', 'url' => ['homeRoom', []]],
    ['label' => 'View room', 'active' => TRUE],
]);
?>

<?= $this->breadcrumbs()->render() ?>

<div class="well">
    <fieldset>
        <div class="panel-body">
            <div class="col-sm-6">
                <legend>
                    <?= $this->escapeHtml($room->getTranslations()->get($localeId)->getSummary()) ?>
                </legend>
                <p><?php
                    $decimalFormatter = new \NumberFormatter(NULL, \NumberFormatter::CURRENCY);
                    $decimalFormatter->setAttribute(\NumberFormatter::FRACTION_DIGITS, 2);
                    ?>
                    <b><?= $this->escapeHtml($this->translate('Price')) ?>:</b>
                    <?= $this->escapeHtml($decimalFormatter->formatCurrency($room->getPrice(), $currency)) ?>
                </p>
                <p>
                    <b><?= $this->escapeHtml($this->translate('Description')) ?>: </b><br>
                    <?= $this->escapeHtml($room->getTranslations()->get($localeId)->getDescription()) ?>
                </p>
            </div>
            <div class="col-sm-6">
                <?php
                $pictureIds = $room->getPictures()->getKeys();
                if (!empty($pictureIds)) {
                    ?>
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <?php foreach ($pictureIds as $key => $pictureId) { ?>
                                <li data-target="#picture" data-slide-to="<?= $key ?>" <?= $key == 0 ? 'class="active"' : '' ?>></li>
                            <?php } ?>

                        </ol>
                        <div class="carousel-inner">
                            <?php foreach ($pictureIds as $key => $pictureId) { ?>
                                <div class="item<?= $key == 0 ? ' active' : '' ?>">
                                    <img src="<?= $this->url(NULL, ['action' => 'getPicture', 'id' => $pictureId]) ?>" alt="Los Angeles">
                                </div>
                            <?php } ?>
                        </div>
                        <a class="left carousel-control" href="#picture" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#picture" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                <?php } ?>
            </div>
        </div>
        <div class="panel-body">
            <?php
            $col = 6;
            foreach ($room->getServices() as $service) {
                if ($service->getTranslations()->containsKey($localeId)) {
                    ?>
                    <div class="col-sm-6">
                        <legend>
                            <?= $this->escapeHtml($service->getTranslations()->get($localeId)->getSummary()) ?>
                        </legend>
                        <p><?php ?>
                            <b><?= $this->escapeHtml($this->translate('Price')) ?>:</b>
                            <?php
                            if ($service->getPrice() == 0) {
                                echo $this->escapeHtml($this->translate('free'));
                            } else {
                                echo $this->escapeHtml($decimalFormatter->formatCurrency($service->getPrice(), $currency));
                            }
                            ?>
                        </p>
                        <p>
                            <b><?= $this->escapeHtml($this->translate('Description')) ?>: </b><br>
                            <?= $this->escapeHtml($service->getTranslations()->get($localeId)->getDescription()) ?>
                        </p>
                    </div>
                    <?php
                    $col = $col == 6 ? 12 : 6;
                }
            }
            ?>
        </div>
    </fieldset>
</div>