<?php
$this->headTitle($this->escapeHtml($this->translate('Add pictures')));
$this->breadcrumbs()->setItems([
    ['label' => 'Pictures', 'icon' => 'picture'],
    ['label' => 'List of pictures', 'url' => ['administrationPicture', []]],
    ['label' => 'Add new picture', 'active' => TRUE],
]);
?>

<?= $this->breadcrumbs()->render() ?>

<div class="well">
    <?= $this->form()->openTag($form) ?>

    <fieldset>
        <legend><?= $this->escapeHtml($this->translate('List of pictures')) ?></legend>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('file')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('file')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('file'), ['class' => 'help-block']) ?>
            </div>
        </div>
    </fieldset>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?= $this->formButton()->openTag($form->get('upload')) ?>
            <span class="glyphicon glyphicon-edit"></span> <?= $this->escapeHtml($this->translate('Upload pictures')) ?>
            <?= $this->formButton()->closeTag() ?>
        </div>
    </div>

    <?= $this->form()->closeTag() ?>
</div>
