<?php
$this->headTitle($this->escapeHtml($this->translate('Pictures')));

$form->setAttributes([
    'onsubmit' => 'return confirm(' . $this->escapeHtml($this->translate('Do you really want to delete picture(s)?')) . ')'
]);
?>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <strong><span class="glyphicon glyphicon-picture"></span> <?= $this->escapeHtml($this->translate('Pictures')) ?>:</strong>
        <li class="breadcrumb-item active" aria-current="page"><?= $this->escapeHtml($this->translate('List of pictures')) ?></li>
    </ol>
</nav>

<div class="well nobottom">
    <?= $this->form()->openTag($form) ?>

    <fieldset>
        <legend><?= $this->escapeHtml($this->translate('List of pictures')) ?></legend>

        <div style="overflow: auto">
            <a class="btn btn-default btn-sm" href="<?= $this->url(NULL, ['action' => 'add']) ?>" style="white-space: nowrap">
                <span class="glyphicon glyphicon-plus"></span> <?= $this->escapeHtml($this->translate('Add new pictures')) ?>
            </a>
            <span class="btn btn-default btn-sm" onclick="(function () {
                        $('input[name=\'pictures&#x5B;&#x5D;\']').click();
                    })()">
                <span class="glyphicon glyphicon-random"></span> <?= $this->escapeHtml($this->translate('Inverse select')) ?>
            </span>
            <?= $this->formButton()->openTag($form->get('remove')) ?>
            <span class="glyphicon glyphicon-trash"></span> <?= $this->escapeHtml($this->translate('Remove selected')) ?>
            <?= $this->formButton()->closeTag() ?>

            <p>
                <?php foreach ($pictures as $picture) { ?>
                <div class="img-thumbnail">
                    <img src="<?= $this->url(NULL, ['action' => 'thumbnail', 'id' => $picture->getId()]) ?>" width="<?= $this->thumbnailWidth ?>">
                    <div class="caption caption-checkbox" data-button="#remove">
                        <label>
                            <input class="icon-checkbox" type="checkbox" name="pictures&#x5B;&#x5D;" value="<?= $picture->getId() ?>"><?= $picture->getId() ?>
                        </label>
                    </div>
                </div>
            <?php } ?>
            </p>
        </div>
    </fieldset>

    <?= $this->form()->closeTag() ?>
</div>

<?= $this->paginationControl($pictures, 'Sliding', 'paginator/paginator', ['route' => NULL, 'queryParams' => $this->pictureQueryManager->getParams()]) ?>
