<?php $this->headTitle($this->escapeHtml($this->translate('Upload photos'))) ?>

<div class="card shadow rounded mb-2 bg-default">
    <div class="card-body">

        <?= $this->form()->openTag($form) ?>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb border border-primary shadow-sm mb-2 p-2">
                <li class="mr-2"><span class="if if-photo bg-default border border-primary rounded-circle p-2 m-n1"></span></li>
                <li class="breadcrumb-item"><a href="<?= $this->url(null, ['action' => 'list']) ?>"><?= $this->escapeHtml($this->translate('List of photos')) ?></a></li>
                <li class="breadcrumb-item active" aria-current="page"><?= $this->escapeHtml($this->translate('Upload photos')) ?></li>
            </ol>
        </nav>

        <div class="card mb-2 bg-default">
            <div class="card-body" style="overflow: auto; height: calc(100vh - 13rem)">

                <div class="form-row">
                    <div class="form-group col-md-12">
                        <?= $this->formLabel($form->get('file')) ?>
                        <?= $this->formElement($form->get('file')) ?>
                        <?= $this->formElementErrors($form->get('file'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                </div>

            </div>
        </div>

        <button type="submit" id="upload" name="upload" class="btn btn-primary">
            <span class="if if-add"></span><?= $this->escapeHtml($this->translate('Upload photos')) ?>
        </button>

        <?= $this->form()->closeTag() ?>

    </div>
</div>
