<?php $this->headTitle($this->escapeHtml($this->translate('View photo'))) ?>

<div class="card shadow rounded mb-2 bg-default">
    <div class="card-body">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb border border-primary shadow-sm mb-2 p-2">
                <li class="mr-2"><span class="if if-photo bg-default border border-primary rounded-circle p-2 m-n1"></span></li>
                <li class="breadcrumb-item"><a href="<?= $this->url(null, ['action' => 'list']) ?>"><?= $this->escapeHtml($this->translate('List of photos')) ?></a></li>
                <li class="breadcrumb-item active" aria-current="page"><?= $this->escapeHtml($this->translate('View photo')) ?></li>
            </ol>
        </nav>

        <div class="card mb-2 bg-default">
            <div class="card-body p-0" style="overflow: auto; height: calc(100vh - 10.7rem)">
                <img class="w-100" src="<?= $this->url('index-photo', ['action' => 'view', 'id' => $this->id]) ?>">
            </div>
        </div>

    </div>
</div>
