<?php
$this->headTitle($this->escapeHtml($this->translate('Your account')));
$this->breadcrumbs()->setItems([
    ['label' => 'Profile', 'icon' => 'wrench'],
    ['label' => 'Account settings', 'active' => TRUE],
]);
?>

<?= $this->breadcrumbs()->render() ?>

<ul class="nav nav-tabs">
    <li role="presentation" class="active">
        <a href="<?= $this->url('profileSettings', ['action' => 'account']) ?>"><?= $this->escapeHtml($this->translate('Account')) ?></a>
    </li>
    <li role="presentation">
        <a href="<?= $this->url('profileSettings', ['action' => 'look']) ?>"><?= $this->escapeHtml($this->translate('Look & feel')) ?></a>
    </li>
</ul>

<div class="well">
    <?= $this->form()->openTag($form) ?>

    <fieldset>
        <legend><?= $this->escapeHtml($this->translate('Account settings')) ?></legend>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('email')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('email')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate('Email address. This is your login either.')) ?>
                </div>
            </div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('email'), ['class' => 'help-block']); ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('realName')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('realName')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate('Real name. Other people will not see if display name is defined.')) ?>
                </div>
            </div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('realName'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('displayName')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('displayName')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate('This is the displayed name that other user will see.')) ?>
                </div>
            </div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('displayName'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('address')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('address')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('address'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('phone')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('phone')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('phone'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('password')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('password')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('password'), ['class' => 'help-block']) ?>
            </div>
        </div>
    </fieldset>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?= $this->formButton()->openTag($form->get('edit')) ?>
            <span class="glyphicon glyphicon-edit"></span> <?= $this->escapeHtml($this->translate('Update your account')) ?>
            <?= $this->formButton()->closeTag() ?>
        </div>
    </div>

    <?= $this->form()->closeTag() ?>
</div>
