<?php
$this->headTitle($this->escapeHtml($this->translate('Look & feel')));
$this->breadcrumbs()->setItems([
    ['label' => 'Profile', 'icon' => 'wrench'],
    ['label' => 'Look & feel', 'active' => TRUE],
]);
?>

<?= $this->breadcrumbs()->render() ?>

<ul class="nav nav-tabs">
    <li role="presentation">
        <a href="<?= $this->url('profileSettings', ['action' => 'account']) ?>"><?= $this->escapeHtml($this->translate('Account')) ?></a>
    </li>
    <li role="presentation" class="active">
        <a href="<?= $this->url('profileSettings', ['action' => 'look']) ?>"><?= $this->escapeHtml($this->translate('Look & feel')) ?></a>
    </li>
</ul>

<div class="well">
    <?= $this->form()->openTag($form) ?>

    <fieldset>
        <legend><?= $this->escapeHtml($this->translate('Look & feel')) ?></legend>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('lookTheme')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('lookTheme')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('lookTheme'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('lookBarStyle')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('lookBarStyle')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('lookBarStyle'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('lookRenderHeader')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('lookRenderHeader')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('lookRenderHeader'), ['class' => 'help-block']) ?>
            </div>
        </div>
    </fieldset>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?= $this->formButton()->openTag($form->get('save')) ?>
            <span class="glyphicon glyphicon-edit"></span> <?= $this->escapeHtml($this->translate('Update look & feel')) ?>
            <?= $this->formButton()->closeTag() ?>
        </div>
    </div>

    <?= $this->form()->closeTag() ?>
</div>
