<nav aria-label="Page navigation">
    <ul class="pagination pagination-sm m-0">
        <?php if (isset($previous)) { ?>
            <li class="page-item">
                <a class="page-link" href="<?= $this->url($this->urlParams[0], $this->urlParams[1], array_merge_recursive($this->urlParams[2], ['query' => ['page' => $previous]])); ?>" aria-label="Previous">
                    <span aria-hidden="true">
                        <span class="if if-backward"></span> <?= $this->escapeHtml($this->translate('Previous')) ?>
                    </span>
                </a>
            </li>
        <?php } else { ?>
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">
                    <span class="if if-backward"></span> <?= $this->escapeHtml($this->translate('Previous')) ?>
                </span>
            </li>
        <?php } ?>

        <?php foreach ($pagesInRange as $page) { ?>
            <?php if ($page != $current) { ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $this->url($this->urlParams[0], $this->urlParams[1], array_merge_recursive($this->urlParams[2], ['query' => ['page' => $page]])); ?>"><?= $this->escapeHtml($page); ?></a>
                </li>
            <?php } else { ?>
                <li class="page-item active">
                    <span class="page-link" aria-hidden="true"><b><?= $this->escapeHtml($page); ?></b></span>
                </li>
            <?php } ?>
        <?php } ?>

        <?php if (isset($next)) { ?>
            <li class="page-item">
                <a class="page-link" href="<?php echo $this->url($this->urlParams[0], $this->urlParams[1], array_merge_recursive($this->urlParams[2], ['query' => ['page' => $next]])); ?>" aria-label="Next">
                    <span aria-hidden="true">
                        <?= $this->escapeHtml($this->translate('Next')) ?> <span class="if if-forward"></span>
                    </span>
                </a>
            </li>
        <?php } else { ?>
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">
                    <?= $this->escapeHtml($this->translate('Next')) ?> <span class="if if-forward"></span>
                </span>
            </li>
        <?php } ?>
    </ul>
</nav>
