<?php if ($pageCount > 1) { ?>
    <?php
    if (!isset($params)) {
        $params = [];
    }
    if (!isset($queryParams)) {
        $queryParams = [];
    }
    ?>
    <nav aria-label="Page navigation">
        <ul class="pagination pagination-sm">
            <?php if (isset($previous)) { ?>
                <li>
                    <a href="<?= $this->url($route, $params, ['query' => $queryParams + ['page' => $previous]]); ?>" aria-label="Previous">
                        <span aria-hidden="true">
                            <span class="glyphicon glyphicon glyphicon-backward"></span> <?= $this->escapeHtml($this->translate('Previous')) ?>
                        </span>
                    </a>
                </li>
            <?php } else { ?>
                <li class="disabled">
                    <span aria-hidden="true">
                        <span class="glyphicon glyphicon glyphicon-backward"></span> <?= $this->escapeHtml($this->translate('Previous')) ?>
                    </span>
                </li>
            <?php } ?>

            <?php foreach ($pagesInRange as $page) { ?>
                <?php if ($page != $current) { ?>
                    <li>
                        <a href="<?= $this->url($route, $params, ['query' => $queryParams + ['page' => $page]]); ?>"><?= $this->escapeHtml($page); ?></a>
                    </li>
                <?php } else { ?>
                    <li class="active">
                        <span aria-hidden="true"><b><?= $this->escapeHtml($page); ?></b></span>
                    </li>
                <?php } ?>
            <?php } ?>

            <?php if (isset($next)) { ?>
                <li>
                    <a href="<?php echo $this->url($route, $params, ['query' => $queryParams + ['page' => $next]]); ?>" aria-label="Next">
                        <span aria-hidden="true">
                            <?= $this->escapeHtml($this->translate('Next')) ?> <span class="glyphicon glyphicon glyphicon-forward"></span>
                        </span>
                    </a>
                </li>
            <?php } else { ?>
                <li class="disabled">
                    <span aria-hidden="true">
                        <?= $this->escapeHtml($this->translate('Next')) ?> <span class="glyphicon glyphicon glyphicon-forward"></span>
                    </span>
                </li>
            <?php } ?>
        </ul>
    </nav>
<?php } ?>