<?php
$this->headTitle($this->escapeHtml($this->translate('Add new service')));
$this->breadcrumbs()->setItems([
    ['label' => 'Services', 'icon' => 'cutlery'],
    ['label' => 'List of services', 'url' => ['administrationService', []]],
    ['label' => 'Add new service', 'active' => TRUE],
]);
?>

<?= $this->breadcrumbs()->render() ?>

<div class="well">
    <?= $this->form()->openTag($form) ?>

    <fieldset>
        <legend><?= $this->escapeHtml($this->translate('Add new service')) ?></legend>

        <div class="form-group right required">
            <div class="col-sm-3"><?= sprintf($this->formLabel($form->get('price')), $currency) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('price')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('price'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-offset-3 col-sm-9">
                <div class="btn-group">
                    <button type="button" class="btn btn-default btn-sm dropdown-toggle disabled" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-globe"></span> <?= $defaultLocaleDisplayName ?> <span class="caret"></span>
                    </button>
                </div>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('summary')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('summary')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('summary'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('description')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('description')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('description'), ['class' => 'help-block']) ?>
            </div>
        </div>
    </fieldset>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?= $this->formButton()->openTag($form->get('add')) ?>
            <span class="glyphicon glyphicon-edit"></span> <?= $this->escapeHtml($this->translate('Add new service')) ?>
            <?= $this->formButton()->closeTag() ?>
        </div>
    </div>

    <?= $this->form()->closeTag() ?>
</div>
