<?php
$this->headTitle($this->escapeHtml($this->translate('Edit service')));
$this->breadcrumbs()->setItems([
    ['label' => 'Services', 'icon' => 'cutlery'],
    ['label' => 'List of services', 'url' => ['administrationService', []]],
    ['label' => 'Edit service', 'active' => TRUE],
]);
?>

<?= $this->breadcrumbs()->render() ?>

<div class="well">
    <?= $this->form()->openTag($form) ?>

    <fieldset>
        <legend><?= $this->escapeHtml($this->translate('Edit service')) ?></legend>

        <div class="form-group right required">
            <div class="col-sm-3"><?= sprintf($this->formLabel($form->get('price')), $currency) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('price')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('price'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-offset-3 col-sm-9">
                <div class="btn-group">
                    <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-globe"></span> <?= $locales[$localeId] ?> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" style="max-height: 10em; overflow: auto">
                        <?php
                        foreach ($locales as $key => $name) {
                            if ($key != $localeId) {
                                ?><li><a href="<?= $this->url(NULL, ['action' => 'edit', 'id' => $id], ['query' => ['localeId' => $key]]) ?>"><?= $name ?></a></li><?php
                            }
                        }
                        ?>
                    </ul>
                </div>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('summary')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('summary')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('summary'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('description')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('description')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('description'), ['class' => 'help-block']) ?>
            </div>
        </div>
    </fieldset>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?= $this->formButton()->openTag($form->get('edit')) ?>
            <span class="glyphicon glyphicon-edit"></span> <?= $this->escapeHtml($this->translate('Edit service')) ?>
            <?= $this->formButton()->closeTag() ?>
        </div>
    </div>

    <?= $this->form()->closeTag() ?>
</div>
