<?php

use Application\Service\Service\ServiceQueryManager;

$this->headTitle($this->escapeHtml($this->translate('Services')));
$this->breadcrumbs()->setItems([
    ['label' => 'Services', 'icon' => 'cutlery'],
    ['label' => 'List of services', 'active' => TRUE],
]);

$form->setAttributes([
    'onsubmit' => 'return confirm(' . $this->escapeHtml($this->translate('Do you really want to delete service(s)?')) . ')'
]);
?>

<?= $this->breadcrumbs()->render() ?>

<div class="well nobottom">
    <?= $this->form()->openTag($form) ?>

    <fieldset>
        <legend><?= $this->escapeHtml($this->translate('List of services')) ?></legend>

        <div style="overflow: auto visible">
            <div class="btn-group">
                <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-globe"></span> <?= $locales[$serviceQueryManager->getLocaleId()] ?> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" style="max-height: 10em; overflow: auto">
                    <?php
                    foreach ($locales as $id => $name) {
                        if ($id != $serviceQueryManager->getLocaleId()) {
                            $queryParams = $this->serviceQueryManager->getParams();
                            $queryParams['localeId'] = $id;
                            ?><li><a href="<?= $this->url(NULL, [], ['query' => $queryParams]) ?>"><?= $name ?></a></li><?php
                        }
                    }
                    ?>
                </ul>
            </div>
            <a class="btn btn-default btn-sm" href="<?= $this->url(NULL, ['action' => 'add']) ?>" style="white-space: nowrap">
                <span class="glyphicon glyphicon-plus"></span> <?= $this->escapeHtml($this->translate('Add new service')) ?>
            </a>
            <span class="btn btn-default btn-sm" onclick="(function () {
                        $('input[name=\'services&#x5B;&#x5D;\']').click();
                    })()">
                <span class="glyphicon glyphicon-random"></span> <?= $this->escapeHtml($this->translate('Inverse select')) ?>
            </span>
            <?= $this->formButton()->openTag($form->get('remove')) ?>
            <span class="glyphicon glyphicon-trash"></span> <?= $this->escapeHtml($this->translate('Remove selected')) ?>
            <?= $this->formButton()->closeTag() ?>

            <table id="service-table" class="table table-hover button-th nobottom">
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th>
                            <?php
                            $icon = '';
                            $queryParams = $this->serviceQueryManager->getParams();
                            if ($queryParams['orderBy'] == ServiceQueryManager::ORDER_BY_ID) {
                                $icon = $queryParams['order'] == ServiceQueryManager::ORDER_ASC ? '-by-attributes' : '-by-attributes-alt';
                                $queryParams['order'] = $queryParams['order'] == ServiceQueryManager::ORDER_ASC ? ServiceQueryManager::ORDER_DESC : ServiceQueryManager::ORDER_ASC;
                            } else {
                                $queryParams['orderBy'] = ServiceQueryManager::ORDER_BY_ID;
                                $queryParams['order'] = ServiceQueryManager::ORDER_ASC;
                            }
                            ?>
                            <a class="btn btn-default btn-sm btn-block" href="<?= $this->url(NULL, [], ['query' => $queryParams]) ?>">
                                <span class="glyphicon glyphicon-sort<?= $icon ?>"></span>
                            </a>
                        </th>
                        <th>
                            <?php
                            $icon = '';
                            $queryParams = $this->serviceQueryManager->getParams();
                            if ($queryParams['orderBy'] == ServiceQueryManager::ORDER_BY_SUMMARY) {
                                $icon = $queryParams['order'] == ServiceQueryManager::ORDER_ASC ? '-by-attributes' : '-by-attributes-alt';
                                $queryParams['order'] = $queryParams['order'] == ServiceQueryManager::ORDER_ASC ? ServiceQueryManager::ORDER_DESC : ServiceQueryManager::ORDER_ASC;
                            } else {
                                $queryParams['orderBy'] = ServiceQueryManager::ORDER_BY_SUMMARY;
                                $queryParams['order'] = ServiceQueryManager::ORDER_ASC;
                            }
                            ?>
                            <a class="btn btn-default btn-sm btn-block" href="<?= $this->url(NULL, [], ['query' => $queryParams]) ?>">
                                <?= $this->escapeHtml($this->translate('Summary')) ?> <span class="glyphicon glyphicon-sort<?= $icon ?>"></span>
                            </a>
                        </th>
                        <th>
                            <?php
                            $icon = '';
                            $queryParams = $this->serviceQueryManager->getParams();
                            if ($queryParams['orderBy'] == ServiceQueryManager::ORDER_BY_PRICE) {
                                $icon = $queryParams['order'] == ServiceQueryManager::ORDER_ASC ? '-by-attributes' : '-by-attributes-alt';
                                $queryParams['order'] = $queryParams['order'] == ServiceQueryManager::ORDER_ASC ? ServiceQueryManager::ORDER_DESC : ServiceQueryManager::ORDER_ASC;
                            } else {
                                $queryParams['orderBy'] = ServiceQueryManager::ORDER_BY_PRICE;
                                $queryParams['order'] = ServiceQueryManager::ORDER_ASC;
                            }
                            ?>
                            <a class="btn btn-default btn-sm btn-block" href="<?= $this->url(NULL, [], ['query' => $queryParams]) ?>">
                                <?= $this->escapeHtml($this->translate('Price')) ?> <span class="glyphicon glyphicon-sort<?= $icon ?>"></span>
                            </a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $decimalFormatter = new \NumberFormatter(NULL, \NumberFormatter::CURRENCY);
                    $decimalFormatter->setAttribute(\NumberFormatter::FRACTION_DIGITS, 2);
                    foreach ($services as $service) {
                        ?>
                        <tr class="active" data-lnk="<?= $this->url(NULL, ['action' => 'edit', 'id' => $service->getId()], $serviceQueryManager->getLocaleId() == 1 ? [] : ['query' => ['localeId' => $serviceQueryManager->getLocaleId()]]) ?>" style="cursor:pointer">
                            <td class="td-checkbox" data-select="true" data-button="#remove">
                                <label>
                                    <input class="icon-checkbox" type="checkbox" name="services&#x5B;&#x5D;" value="<?= $service->getId() ?>">
                                </label>
                            </td>
                            <td><?= $this->escapeHtml($service->getId()) ?></td>
                            <td>
                                <?php
                                $localeId = $this->serviceQueryManager->getLocaleId();
                                $summary = $service->getTranslations()->containsKey($localeId) ? $service->getTranslations()->get($localeId)->getSummary() : $this->translate('*** undefined ***');
                                echo $this->escapeHtml($summary);
                                ?>
                            </td>
                            <td><?= $this->escapeHtml($decimalFormatter->formatCurrency($service->getPrice(), $currency)) ?></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </fieldset>

    <?= $this->form()->closeTag() ?>
</div>

<?= $this->paginationControl($services, 'Sliding', 'paginator/paginator', ['route' => NULL, 'queryParams' => $this->serviceQueryManager->getParams()]) ?>
