<?php $this->headTitle($this->escapeHtml($this->translate('Features and options'))) ?>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <strong><span class="glyphicon glyphicon-dashboard"></span> <?= $this->escapeHtml($this->translate('Dashboard')) ?>:</strong>
        <li class="breadcrumb-item active" aria-current="page"><?= $this->escapeHtml($this->translate('Features')) ?></li>
    </ol>
</nav>

<ul class="nav nav-tabs">
    <li role="presentation" class="active">
        <a href="<?= $this->url(NULL, ['action' => 'features']) ?>"><?= $this->escapeHtml($this->translate('Features')) ?></a>
    </li>
    <li role="presentation">
        <a href="<?= $this->url(NULL, ['action' => 'look']) ?>"><?= $this->escapeHtml($this->translate('Look & feel')) ?></a>
    </li>
</ul>

<div class="well">
    <?= $this->form()->openTag($form) ?>

    <fieldset>
        <legend><?= $this->escapeHtml($this->translate('Company information')) ?></legend>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('companyName')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('companyName')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('companyName'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('companyI18n')) ?></div>
            <div class="col-sm-9">
                <div class="checkbox">
                    <label>
                        <?= $this->formElement($form->get('companyI18n')); ?>
                        <?= $this->escapeHtml($this->translate('Enabling brand name translation')) ?>
                    </label>
                </div>
            </div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('companyI18n'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('companyFullName')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('companyFullName')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('companyFullName'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('companyEmail')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('companyEmail')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('companyEmail'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('companyAddress')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('companyAddress')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('companyAddress'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('companyPhone')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('companyPhone')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('companyPhone'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('companyCurrency')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('companyCurrency')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('companyCurrency'), ['class' => 'help-block']) ?>
            </div>
        </div>
    </fieldset>

    <fieldset>
        <legend><?= $this->escapeHtml($this->translate('Upload information')) ?></legend>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('uploadJpegQuality')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('uploadJpegQuality')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate('Quality of the images. 1 is the lowest, 100 is the highest.')) ?>
                </div>
                <?= $this->formElementErrors($form->get('uploadJpegQuality'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('uploadMinImageSize')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('uploadMinImageSize')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate('Minimum image width or height.')) ?>
                </div>
                <?= $this->formElementErrors($form->get('uploadMinImageSize'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('uploadMaxImageSize')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('uploadMaxImageSize')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate('Maximum image width or height.')) ?>
                </div>
                <?= $this->formElementErrors($form->get('uploadMaxImageSize'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right required">
            <div class="col-sm-3"><?= $this->formLabel($form->get('uploadThumbnailWidth')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('uploadThumbnailWidth')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('uploadThumbnailWidth'), ['class' => 'help-block']) ?>
            </div>
        </div>

    </fieldset>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?= $this->formButton()->openTag($form->get('save')) ?>
            <span class="glyphicon glyphicon-edit"></span> <?= $this->escapeHtml($this->translate('Update features and options')) ?>
            <?= $this->formButton()->closeTag() ?>
        </div>
    </div>

    <?= $this->form()->closeTag() ?>
</div>
