<?php $this->headTitle('Google maps') ?>

<div class="page-header">
    <h1 id="dashboard">
        <span class="glyphicon glyphicon-dashboard"></span> <?= $this->escapeHtml($this->translate('Dashboard')) ?>
    </h1>
</div>

<ul class="nav nav-tabs well-tabs">
    <li role="presentation">
        <a href="<?= $this->url('administrationDashboard', ['action' => 'company']) ?>"><?= $this->escapeHtml($this->translate('Company')) ?></a>
    </li>
    <li role="presentation" class="active">
        <a href="<?= $this->url('administrationDashboard', ['action' => 'google']) ?>"><?= $this->escapeHtml($this->translate('Google')) ?></a>
    </li>
    <li role="presentation">
        <a href="<?= $this->url('administrationDashboard', ['action' => 'look']) ?>"><?= $this->escapeHtml($this->translate('Look & feel')) ?></a>
    </li>
</ul>

<div class="well tabs-well">
    <?= $this->form()->openTag($form) ?>
    <fieldset>
        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('latitude')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('latitude')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate('The latitude GPS coordinate is between -90 and 90.')) ?>
                </div>
            </div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('latitude'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('longitude')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('longitude')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate('The longitude GPS coordinate is between -180 and 180.')) ?>
                </div>
            </div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('longitude'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group right">
            <div class="col-sm-3"><?= $this->formLabel($form->get('zoom')) ?></div>
            <div class="col-sm-9"><?= $this->formElement($form->get('zoom')) ?></div>
            <div class="col-sm-offset-3 col-sm-9">
                <div class="help-block nobottom">
                    <?= $this->escapeHtml($this->translate('15 is generally good zoom value.')) ?>
                </div>
            </div>
            <div class="col-sm-offset-3 col-sm-9">
                <?= $this->formElementErrors($form->get('zoom'), ['class' => 'help-block']) ?>
            </div>
        </div>
    </fieldset>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <button class="btn btn-primary" type="submit" name="save">
                <span class="glyphicon glyphicon-edit"></span> <?= $this->escapeHtml($this->translate(sprintf('Update %s', $this->translate('Google maps')))) ?>
            </button>
        </div>
    </div>
    <?= $this->form()->closeTag() ?>
</div>
