<?php $this->headTitle('Dashboard') ?>

<div class="row" style="padding-top: 15px;">
    <div class="col-md-8 center-block" style="float:none">
        <div class="well">
            <?= $this->form()->openTag($form) ?>
            <fieldset>
                <legend><?= $this->escapeHtml('Company information') ?></legend>

                <div class="form-group right required">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('brandName')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('brandName')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('brandName'), ['class' => 'help-block']) ?>
                    </div>
                </div>

                <div class="form-group right required">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('email')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('email')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('email'), ['class' => 'help-block']) ?>
                    </div>
                </div>

                <div class="form-group right required">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('address')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('address')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('address'), ['class' => 'help-block']) ?>
                    </div>
                </div>

                <div class="form-group right required">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('phone')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('phone')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('phone'), ['class' => 'help-block']) ?>
                    </div>
                </div>
            </fieldset>

            <fieldset>
                <legend><?= $this->escapeHtml('Google maps') ?></legend>

                <div class="form-group right">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('latitude')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('latitude')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <div class="help-block nobottom">
                            <?= $this->escapeHtml($this->translate('The latitude GPS coordinate is between -90 and 90.')) ?>
                        </div>
                    </div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('latitude'), ['class' => 'help-block']) ?>
                    </div>
                </div>

                <div class="form-group right">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('longitude')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('longitude')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <div class="help-block nobottom">
                            <?= $this->escapeHtml($this->translate('The longitude GPS coordinate is between -180 and 180.')) ?>
                        </div>
                    </div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('longitude'), ['class' => 'help-block']) ?>
                    </div>
                </div>

                <div class="form-group right">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('zoom')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('zoom')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <div class="help-block nobottom">
                            <?= $this->escapeHtml($this->translate('15 is generally good zoom value.')) ?>
                        </div>
                    </div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('zoom'), ['class' => 'help-block']) ?>
                    </div>
                </div>
            </fieldset>

            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    <button class="btn btn-primary" type="submit" name="save">
                        <span class="glyphicon glyphicon-edit"></span> <?= $this->escapeHtml($this->translate('Save options')) ?>
                    </button>
                </div>
            </div>
            <?= $this->form()->closeTag() ?>
        </div>
    </div>
</div>


