<?php $this->headTitle($this->escapeHtml($this->translate('Your look & feel'))) ?>

<div class="card shadow rounded mb-2 bg-default">
    <div class="card-body">

        <?= $this->form()->openTag($form) ?>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb border border-secondary shadow-sm mb-2 p-2">
                <li class="mr-2"><span class="if if-look bg-white border border-secondary rounded-circle p-2 m-n1"></span></li>
                <li class="breadcrumb-item active" aria-current="page"><?= $this->escapeHtml($this->translate('Your look & feel')) ?></li>
            </ol>
        </nav>

        <div class="card mb-2 bg-default">
            <div class="card-body" style="overflow: auto; height: calc(100vh - 13rem)">

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('theme')) ?>
                        <?= $this->formElement($form->get('theme')) ?>
                        <?= $this->formElementErrors($form->get('theme'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('barStyle')) ?>
                        <?= $this->formElement($form->get('barStyle')) ?>
                        <?= $this->formElementErrors($form->get('barStyle'), ['class' => 'alert alert-warning border mb-0 p-2 pl-4']) ?>
                    </div>
                </div>

            </div>
        </div>

        <button type="submit" id="update" name="update" class="btn btn-primary">
            <span class="if if-update"></span><?= $this->escapeHtml($this->translate('Update look & feel')) ?>
        </button>

        <?= $this->form()->closeTag() ?>

    </div>
</div>
