<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->brandName)->setSeparator(' - ')->setAutoEscape(false) ?>
        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/coffee-theme.min.css'))
        ?>
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/clock.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <?php
        if (isset($activeMenuItemId)) {
            $this->navMenu()->setActiveItemId($activeMenuItemId);
        }
        ?>
        <?= $this->navBar()->render() ?>

        <div class="container">
            <?= $this->header()->render() ?>
            <?= $this->content ?>
        </div>
        <?=
                $this->inlineScript()
                ->prependScript('$(document).ready(initClock())')
        ?>
        <script></script>
    </body>
</html>
