<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->titleString)->setSeparator(' - ')->setAutoEscape(FALSE) ?>
        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('themes/' . $this->themeString . '/css/style.css'))
                ->prependStylesheet($this->basePath('themes/' . $this->themeString . '/css/theme.css'))
        ?>
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/scripts.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <?= $this->navigationBar($this->activeMenuItemId) ?>
        <div class="container">
            <div class="row">
                <div class="col-md-10 center-block" style="float:none">
                    <?= $this->header() ?>
                    <?= $this->content ?>
                </div>
            </div>
        </div>
    </body>
</html>
