<?php $this->headTitle('Users');

$orders = [
    'id' => 'ASC',
    'realName' => 'ASC',
    'email' => 'ASC',
    'role' => 'ASC',
];
$orders[$orderBy] = $order == 'ASC' ? 'DESC' : 'ASC';
$sortIcons = [
    'id' => '',
    'realName' => '',
    'email' => '',
    'role' => '',
];
$sortIcons[$orderBy] = $order == 'ASC' ? '-by-attributes' : '-by-attributes-alt'
?>

<div class="page-header">
    <h2 id="users"><?= $this->escapeHtml($this->translate('Users')) ?></h2>
</div>

<div class="row">
    <div class="col-sm-12 center-block" style="float:none">
        <div class="well nobottom">
            <div class="overflow-auto">
                <table id="myTable" class="table table-hover nobottom">
                    <thead>
                        <tr>
                            <th style="white-space: nowrap">
                                <a href="<?= $this->url('admin-users', [], ['query' => ['orderBy' => 'id', 'order' => $orders['id']]]) ?>">
                                    <span class="glyphicon glyphicon-sort<?= $sortIcons['id'] ?>"></span>
                                </a>
                            </th>
                            <th style="white-space: nowrap">
                                <?= $this->escapeHtml($this->translate('Name')) ?>
                                <a href="<?= $this->url('admin-users', [], ['query' => ['orderBy' => 'realName', 'order' => $orders['realName']]]) ?>">
                                    <span class="glyphicon glyphicon-sort<?= $sortIcons['realName'] ?>"></span>
                                </a>
                            </th>
                            <th style="white-space: nowrap">
                                <?= $this->escapeHtml($this->translate('Email')) ?>
                                <a href="<?= $this->url('admin-users', [], ['query' => ['orderBy' => 'email', 'order' => $orders['email']]]) ?>">
                                    <span class="glyphicon glyphicon-sort<?= $sortIcons['email'] ?>"></span>
                                </a>
                            </th>
                            <th style="white-space: nowrap">
                                <?= $this->escapeHtml($this->translate('Role')) ?>
                                <a href="<?= $this->url('admin-users', [], ['query' => ['orderBy' => 'role', 'order' => $orders['role']]]) ?>">
                                    <span class="glyphicon glyphicon-sort<?= $sortIcons['role'] ?>"></span>
                                </a>
                            </th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($users as $user) { ?>
                            <tr class="active">
                                <td><?= $this->escapeHtml($user->getId()) ?></td>
                                <td><?= $this->escapeHtml($user->getRealName()) ?></td>
                                <td><?= $this->escapeHtml($user->getEmail()) ?></td>
                                <td><?= $this->escapeHtml($user->getRole()) ?></td>
                                <td>
                                    <a href="<?= $this->url('admin-users', array('action' => 'edit', 'id' => $user->getId())) ?>" style="white-space: nowrap">
                                        <span class="glyphicon glyphicon-edit"></span> <?= $this->escapeHtml($this->translate('Edit')) ?></a>&nbsp;
                                    <a href="<?= $this->url('admin-users', array('action' => 'remove', 'id' => $user->getId())) ?>" style="white-space: nowrap">
                                        <span class="glyphicon glyphicon-remove"></span> <?= $this->escapeHtml($this->translate('Remove')) ?></a>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
        <?= $this->paginationControl($users, 'Sliding', 'paginator/paginator', ['route' => 'admin-users', 'requiredQuery' => $requiredQuery]) ?>
    </div>
</div>
