<?php
$this->headTitle($this->escapeHtml($this->translate('Edit reservation')));
$this->breadcrumbs()->setItems([
    ['label' => 'Reservations', 'icon' => 'pushpin'],
    ['label' => 'List of reservations', 'url' => ['profileReservation', []]],
    ['label' => 'Edit reservation', 'active' => TRUE],
]);
?>

<?= $this->breadcrumbs()->render() ?>

<div class="well">
    <fieldset>
        <div class="panel-body">
            <div class="col-sm-6">
                <legend>
                    <?= $this->escapeHtml($room->getTranslations()->get($localeId)->getSummary()) ?>
                </legend>
                <p>
                    <?php
                    $decimalFormatter = new \NumberFormatter(NULL, \NumberFormatter::CURRENCY);
                    $decimalFormatter->setAttribute(\NumberFormatter::FRACTION_DIGITS, 2);
                    ?>
                    <b><?= $this->escapeHtml($this->translate('Price')) ?>:</b>
                    <?= $this->escapeHtml($decimalFormatter->formatCurrency($room->getPrice(), $currency)) ?>
                </p>
                <p>
                    <b><?= $this->escapeHtml($this->translate('Description')) ?>: </b><br>
                    <?= $this->escapeHtml($room->getTranslations()->get($localeId)->getDescription()) ?>
                </p>
            </div>
            <div class="col-sm-6">
                <?php
                $this->reservationCalendar()->setDate($year, $month, $yearLimit);
                $this->reservationCalendar()->setId($room->getId());
                ?>
                <?= $this->reservationCalendar()->render() ?>
            </div>
        </div>
    </fieldset>
</div>