<?php
$this->headTitle('Sign in');

$form->get('email')->setAttributes([
            'class' => 'form-control',
            'placeholder' => $this->escapeHtml($this->translate('Email address')),
            'required' => true,
            'autofocus' => true
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);

$form->get('password')->setAttributes([
            'class' => 'form-control',
            'placeholder' => $this->escapeHtml($this->translate('Password')),
            'required' => true,
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);
?>

<div class="page-header">
    <h2 id="login"><?= $this->translate('Sign in') ?></h2>
</div>

<div class="row">
    <div class="col-sm-6 center-block" style="float:none">
        <div class="well">
            <?= $this->form()->openTag($form) ?>
            <?php
            $feedback = [
                'email' => [
                    'type' => '',
                    'icon' => ''
                ],
                'password' => [
                    'type' => '',
                    'icon' => ''
                ],
            ];
            if ($isLoginError) {
                if ($this->formElementErrors($form->get('email'))) {
                    $feedback['email']['type'] = 'error';
                    $feedback['email']['icon'] = 'remove';
                } else {
                    $feedback['email']['type'] = 'success';
                    $feedback['email']['icon'] = 'ok';
                }
                if ($this->formElementErrors($form->get('password'))) {
                    $feedback['password']['type'] = 'error';
                    $feedback['password']['icon'] = 'remove';
                } else {
                    $feedback['password']['type'] = 'success';
                    $feedback['password']['icon'] = 'ok';
                }
                if (($feedback['email']['icon'] == 'ok') && ($feedback['password']['icon'] == 'ok')) {
                    ?>
                    <div class="alert alert-warning" role="alert">
                        <?= $this->translate('Incorrect email and/or password.') ?>
                        <a href="<?= $this->url('auth-reset-password') ?>"><?= $this->translate('Forgot password?') ?></a>
                    </div>
                    <?php
                }
            }
            ?>

            <fieldset>
                <legend><?= $this->escapeHtml($this->translate('Please sign in')) ?></legend>
                <div class="form-group has-<?= $feedback['email']['type'] ?> has-feedback">
                    <?= $this->formLabel($form->get('email')); ?>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                        <?= $this->formElement($form->get('email')); ?>
                    </div>
                    <span class="glyphicon glyphicon-<?= $feedback['email']['icon'] ?> form-control-feedback"></span>
                    <?= $this->formElementErrors($form->get('email'), ['class' => 'help-block']); ?>
                </div>

                <div class="form-group has-<?= $feedback['password']['type'] ?> has-feedback">
                    <?= $this->formLabel($form->get('password')); ?>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <?= $this->formElement($form->get('password')); ?>
                    </div>
                    <span class="glyphicon glyphicon-<?= $feedback['password']['icon'] ?> form-control-feedback"></span>
                    <?= $this->formElementErrors($form->get('password'), ['class' => 'help-block']); ?>
                </div>

                <div class="checkbox">
                    <label>
                        <?= $this->formElement($form->get('remember_me')); ?> <?= $this->escapeHtml($this->translate('Remember me')) ?>
                    </label>
                </div>
                <?= $this->formElement($form->get('redirect_url')); ?>
                <?= $this->formElement($form->get('csrf')) ?>
                <button class="btn btn-lg btn-primary btn-block" type="submit">
                    <span class="glyphicon glyphicon-log-in"></span> <?= $this->escapeHtml($this->translate('Sign in')) ?>
                </button>
            </fieldset>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
