<?php $this->headTitle('Sign in') ?>

<div class="page-header">
    <h1 id="login"><?= $this->translate('Sign in') ?></h1>
</div>

<div class="row">
    <div class="col-md-8 center-block" style="float:none">
        <div class="well">
            <?= $this->form()->openTag($form) ?>
            <fieldset>
                <legend><?= $this->escapeHtml($this->translate('Please sign in')) ?></legend>
                <?php if ($isLoginError) { ?>
                    <div class="alert alert-warning" role="alert">
                        <?= $this->translate('Incorrect email and/or password.') ?>
                        <a href="<?= $this->url('auth-reset-password') ?>"><?= $this->translate('Forgot password?') ?></a>
                    </div>
                <?php } ?>

                <div class="form-group right required">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('email')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('email')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <div class="help-block nobottom">
                            <?= $this->escapeHtml($this->translate('Email address. This is your login either.')) ?>
                        </div>
                    </div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('email'), ['class' => 'help-block']); ?>
                    </div>
                </div>

                <div class="form-group right required">
                    <div class="col-sm-3"><?= $this->formLabel($form->get('password')) ?></div>
                    <div class="col-sm-9"><?= $this->formElement($form->get('password')) ?></div>
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= $this->formElementErrors($form->get('password'), ['class' => 'help-block']) ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <div class="checkbox">
                            <label>
                                <?= $this->formElement($form->get('remember_me')); ?> <?= $this->escapeHtml($this->translate('Remember me')) ?>
                            </label>
                        </div>
                    </div>
                </div>

                <?= $this->formElement($form->get('redirect_url')) ?>
                <?= $this->formElement($form->get('csrf')) ?>

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <button class="btn btn-primary" type="submit">
                            <span class="glyphicon glyphicon-log-in"></span> <?= $this->escapeHtml($this->translate('Sign in')) ?>
                        </button>
                    </div>
                </div>

            </fieldset>
            <?= $this->form()->closeTag() ?>
        </div>
    </div>
</div>
