<?php
$this->headTitle('Sign in');

$form->get('email')->setAttributes([
            'class' => 'form-control',
            'placeholder' => 'Email address',
            'required' => true,
            'autofocus' => true
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);

$form->get('password')->setAttributes([
            'class' => 'form-control',
            'placeholder' => 'Password',
            'required' => true,
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);
?>

<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <h2 class="form-signin-heading">Please sign in</h2>
        <?= $this->form()->openTag($form) ?>
        <?php
        $feedback = [
            'email' => [
                'type' => '',
                'icon' => ''
            ],
            'password' => [
                'type' => '',
                'icon' => ''
            ],
        ];
        if ($isLoginError) {
            if ($this->formElementErrors($form->get('email'))) {
                $feedback['email']['type'] = 'error';
                $feedback['email']['icon'] = 'remove';
            } else {
                $feedback['email']['type'] = 'success';
                $feedback['email']['icon'] = 'ok';
            }
            if ($this->formElementErrors($form->get('password'))) {
                $feedback['password']['type'] = 'error';
                $feedback['password']['icon'] = 'remove';
            } else {
                $feedback['password']['type'] = 'success';
                $feedback['password']['icon'] = 'ok';
            }
            if (($feedback['email']['icon'] == 'ok') && ($feedback['password']['icon'] == 'ok')) {
                ?>
                <div class="alert alert-warning" role="alert">
                    Incorrect login and/or password.
                    <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
                </div>
                <?php
            }
        }
        ?>

        <div class="form-group has-<?= $feedback['email']['type'] ?> has-feedback">
            <?= $this->formLabel($form->get('email')); ?>
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                <?= $this->formElement($form->get('email')); ?>
            </div>
            <span class="glyphicon glyphicon-<?= $feedback['email']['icon'] ?> form-control-feedback"></span>
            <?= $this->formElementErrors($form->get('email'), array('class' => 'help-block')); ?>
        </div>

        <div class="form-group has-<?= $feedback['password']['type'] ?> has-feedback">
            <?= $this->formLabel($form->get('password')); ?>
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                <?= $this->formElement($form->get('password')); ?>
            </div>
            <span class="glyphicon glyphicon-<?= $feedback['password']['icon'] ?> form-control-feedback"></span>
            <?= $this->formElementErrors($form->get('password'), array('class' => 'help-block')); ?>
        </div>

        <div class="checkbox">
            <label>
                <?= $this->formElement($form->get('remember_me')); ?> Remember me
            </label>
        </div>
        <?= $this->formElement($form->get('redirect_url')); ?>
        <?= $this->formElement($form->get('csrf')) ?>
        <button class="btn btn-lg btn-primary btn-block" type="submit">
            <span class="glyphicon glyphicon-log-in"></span> Sign in</button>
            <?= $this->form()->closeTag(); ?>
    </div>
</div>
