<?php
$this->headTitle('Home');
?>

<div class="panel panel-default" style="margin-top: 15px;">
    <div class="panel-heading"><?= $this->escapeHtml($this->translate('Contact information:')) ?></div>
    <div class="panel-body">
        <?php if (count($hotel)) { ?>
            <ul style="list-style-type: none;padding: 0">
                <?= $hotel['address'] ? '<li><span class="glyphicon glyphicon-home"></span> ' . $this->escapeHtml($hotel['address']) . '</li>' : '' ?>
                <?= $hotel['email'] ? '<li><span class="glyphicon glyphicon-envelope"></span> ' . $this->escapeHtml($hotel['email']) . '</li>' : '' ?>
                <?= $hotel['phone'] ? '<li><span class="glyphicon glyphicon-phone-alt"></span> ' . $this->escapeHtml($hotel['phone']) . '</li>' : '' ?>
            </ul>
        <?php } ?>
        <?php if ($googleMap) { ?>
            <div id="map" class="google-map"></div>
        <?php } ?>
    </div>
</div>
<script>
    function initMap() {
        var uluru = {lat: <?= $this->escapeHtml($googleMap['lat']) ?>, lng: <?= $this->escapeHtml($googleMap['lng']) ?>};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: <?= $this->escapeHtml($googleMap['zoom']) ?>,
            center: uluru
        });
        var marker = new google.maps.Marker({
            position: uluru,
            map: map
        });
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?callback=initMap">
</script>
