<?php

use Application\Service\Option\SettingsManager;

$this->headTitle($this->escapeHtml($this->translate($this->action == 'add' ? 'Add service(s) to room' : 'Remove service(s) from room')));
?>
<div class="card shadow rounded mb-2 bg-default">
    <div class="card-body">

        <?= $this->form()->openTag($form) ?>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb border border-primary shadow-sm mb-2 p-2">
                <li class="mr-2"><span class="if if-room bg-default border border-primary rounded-circle p-2 m-n1"></span></li>
                <li class="breadcrumb-item"><a href="<?= $this->url(null, ['action' => 'list'], ['query' => ['locale' => $this->locale]]) ?>"><?= $this->escapeHtml($this->translate('List of rooms')) ?></a></li>
                <li class="breadcrumb-item"><a href="<?= $this->url(null, ['action' => 'edit', 'id' => $this->roomId], ['query' => ['locale' => $this->locale]]) ?>"><?= $this->escapeHtml($this->translate('Edit room')) ?></a></li>
                <li class="breadcrumb-item active" aria-current="page"><?= $this->escapeHtml($this->translate($this->action == 'add' ? 'Add service(s) to room' : 'Remove service(s) from room')) ?></li>
            </ol>
        </nav>

        <div class="btn-group mb-2" role="group">
            <div class="btn-group">
                <button typy="button" class="btn btn-sm btn-outline-primary dropdown-toggle" id="localeDropdown" data-toggle="dropdown">
                    <span class="if if-locale"></span><?= $this->escapeHtml($this->settingsManager->getSetting(SettingsManager::LOCALE_NAMES)[$this->serviceQueryManager->getLocale()]) ?> <span class="caret"></span>
                </button>
                <div class="dropdown-menu" aria-labelledby="localeDropdown" style="max-height: 10em; overflow: auto">
                    <?php foreach ($this->settingsManager->getSetting(SettingsManager::LOCALE_NAMES) as $locale => $localeName) { ?>
                        <?php if ($locale != $this->serviceQueryManager->getLocale()) { ?>
                            <a class="dropdown-item" href="<?= $this->url(null, ['action' => 'edit-services', 'id' => $this->roomId], ['query' => array_merge($this->serviceQueryManager->getParams(['locale' => $locale]), ['action' => $this->action])]) ?>"><?= $this->escapeHtml($localeName) ?></a>
                        <?php } ?>
                    <?php } ?>
                </div>
            </div>
            <a role="button" class="btn btn-sm btn-outline-primary" href="<?= $this->url(null, ['action' => 'edit-services', 'id' => $this->roomId], ['query' => array_merge($this->serviceQueryManager->getParams(), ['action' => $this->action == 'add' ? 'remove' : 'add'])]) ?>">
                <span class="if if-list"></span><?= $this->escapeHtml($this->translate($this->action == 'add' ? 'List selected services' : 'List available services')) ?>
            </a>
            <button type="button" class="btn btn-sm btn-outline-primary" data-toggle="checkbox" data-target="[name='services[]']">
                <span class="if if-inverse"></span><?= $this->escapeHtml($this->translate('Inverse select')) ?>
            </button>
            <button type="submit" id="<?= $this->action ?>" name="<?= $this->action ?>" class="btn btn-sm btn-outline-primary" data-hide="[name='services[]']" style="display: none">
                <span class="if if-<?= $this->action ?>"></span><?= $this->escapeHtml($this->translate($this->action == 'add' ? 'Add selected' : 'Remove selected')) ?>
            </button>
        </div>

        <div class="card mb-2 bg-default">
            <div class="card-body" style="overflow: auto; height: calc(100vh - 15rem)">

                <table id="service-table" class="table table-hover table-sm" style="min-width: 30rem">
                    <thead>
                        <tr>
                            <th scope="col">&nbsp</th>
                            <?php foreach ($this->serviceQueryManager->getColumnNameList() as $idx => $columnName) { ?>
                                <?php
                                $orderBy = $this->serviceQueryManager->getOrderByList()[$idx];
                                $order = $this->serviceQueryManager->getOrderBy() == $orderBy ? '%INVERSE%' : '%DEFAULT%';
                                $icon = $this->serviceQueryManager->getOrderBy() == $orderBy ? strtolower($this->serviceQueryManager->getOrder()) : 'blank';
                                ?>
                                <th scope="col" data-href="<?= $this->url(null, ['action' => 'edit-services', 'id' => $this->roomId], ['query' => array_merge($this->serviceQueryManager->getParams(['orderBy' => $orderBy, 'order' => $order]), ['action' => $this->action])]) ?>">
                                    <?= $this->escapeHtml($this->translate($columnName)) ?><span class="if if-<?= $icon ?> ml-1"></span>
                                </th>
                            <?php } ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->services as $service) { ?>
                            <tr>
                                <td>
                                    <div class="custom-control custom-checkbox">
                                        <input class="custom-control-input" type="checkbox" id="service<?= $service->getId() ?>" name="services[]" value="<?= $service->getId() ?>">
                                        <label class="custom-control-label" for="service<?= $service->getId() ?>"></label>
                                    </div>
                                </td>
                                <?php foreach ($this->serviceQueryManager->getColumnIdList() as $columnId) { ?>
                                    <td data-href="<?= $this->url('admin-service', ['action' => 'edit', 'id' => $service->getId()], ['query' => ['locale' => $this->serviceQueryManager->getLocale()]]) ?>">
                                        <?= $this->escapeHtml($service->get(str_replace('translation', 'translation.' . $this->serviceQueryManager->getLocale(), $columnId))) ?>
                                    </td>
                                <?php } ?>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>

            </div>
        </div>

        <?= $this->form()->closeTag() ?>

        <?= $this->paginationControl($this->services, 'Sliding', 'paginator/paginator', ['urlParams' => [null, [], ['query' => $this->serviceQueryManager->getParams()]]]) ?>

    </div>
</div>
